# Uncomment the next line to define a global platform for your project
 platform :osx, '10.12'

target 'SwiftQQ' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  pod 'SnapKit', '~> 4.0.0'

end
